
package service.services.soap.LoginService.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginService", targetNamespace = "http://common.dip.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginService {


    /**
     * 
     * @param user
     * @return
     *     returns service.services.soap.LoginService.common.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doLogin", targetNamespace = "http://common.dip.com/", className = "service.services.soap.LoginService.common.DoLogin")
    @ResponseWrapper(localName = "doLoginResponse", targetNamespace = "http://common.dip.com/", className = "service.services.soap.LoginService.common.DoLoginResponse")
    public User doLogin(
        @WebParam(name = "user", targetNamespace = "")
        User user);

}
